spring:
  application:
    name: banking
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://165.22.66.209:5432/banking?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: dtb
    password: dtb2025
    hikari:
      data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
  jpa:
    hibernate:
        ddl-auto: update
#        naming:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
